// Code generated by pnpm gen:exec-arg-pattern:swift. DO NOT EDIT.

enum ExecArgPatternSafetyJS {
    static let source = #"""
"use strict";
var OpenClawExecArgPattern = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/infra/exec-arg-pattern.ts
  var exec_arg_pattern_exports = {};
  __export(exec_arg_pattern_exports, {
    compileExecArgPattern: () => compileExecArgPattern,
    isConservativeExecArgPatternRefusal: () => isConservativeExecArgPatternRefusal
  });

  // packages/normalization-core/src/expect.ts
  function expectDefined(value, context) {
    if (value === null || value === void 0) {
      throw new Error("expected " + context + " to be defined");
    }
    return value;
  }

  // packages/normalization-core/src/number-coercion.ts
  var MAX_TIMER_TIMEOUT_MS = 2147e6;
  var MAX_TIMER_TIMEOUT_SECONDS = Math.floor(MAX_TIMER_TIMEOUT_MS / 1e3);

  // src/infra/map-size.ts
  function pruneMapToMaxSize(map, maxSize) {
    if (Number.isNaN(maxSize) || maxSize === Number.POSITIVE_INFINITY) {
      return;
    }
    const limit = Math.max(0, Math.floor(maxSize));
    if (limit <= 0) {
      map.clear();
      return;
    }
    if (map.size <= limit) {
      return;
    }
    const keys = map.keys();
    while (map.size > limit) {
      const oldest = keys.next();
      if (oldest.done) {
        break;
      }
      map.delete(oldest.value);
    }
  }

  // src/security/safe-regex-tokens.ts
  function readGroupContentStart(source, index) {
    if (source[index + 1] !== "?") {
      return index + 1;
    }
    const marker = source[index + 2];
    if (marker === ":" || marker === "=" || marker === "!") {
      return index + 3;
    }
    if (marker !== "<") {
      return index + 1;
    }
    if (source[index + 3] === "=" || source[index + 3] === "!") {
      return index + 4;
    }
    const nameEnd = source.indexOf(">", index + 3);
    return nameEnd === -1 ? index + 1 : nameEnd + 1;
  }
  function readQuantifier(source, index) {
    const ch = source[index];
    const consumed = source[index + 1] === "?" ? 2 : 1;
    if (ch === "*") {
      return { consumed, minRepeat: 0, maxRepeat: null };
    }
    if (ch === "+") {
      return { consumed, minRepeat: 1, maxRepeat: null };
    }
    if (ch === "?") {
      return { consumed, minRepeat: 0, maxRepeat: 1 };
    }
    if (ch !== "{") {
      return null;
    }
    let i = index + 1;
    while (i < source.length && /\d/.test(source.charAt(i))) {
      i += 1;
    }
    if (i === index + 1) {
      return null;
    }
    const minRepeat = Number.parseInt(source.slice(index + 1, i), 10);
    let maxRepeat = minRepeat;
    if (source[i] === ",") {
      i += 1;
      const maxStart = i;
      while (i < source.length && /\d/.test(source.charAt(i))) {
        i += 1;
      }
      maxRepeat = i === maxStart ? null : Number.parseInt(source.slice(maxStart, i), 10);
    }
    if (source[i] !== "}") {
      return null;
    }
    i += 1;
    if (source[i] === "?") {
      i += 1;
    }
    if (maxRepeat !== null && maxRepeat < minRepeat) {
      return null;
    }
    return { consumed: i - index, minRepeat, maxRepeat };
  }
  function isUnicodePropertyName(interior) {
    return /^[A-Za-z_][A-Za-z0-9_]*(=[A-Za-z0-9_]+)?$/.test(interior);
  }
  function readEscapeAtomEnd(source, backslashIndex, unicodeMode = false, captureCount = 0) {
    if (backslashIndex + 1 >= source.length) {
      return backslashIndex;
    }
    const kind = source[backslashIndex + 1];
    const afterKind = backslashIndex + 2;
    if ((kind === "p" || kind === "P") && source[afterKind] === "{") {
      if (!unicodeMode) {
        return backslashIndex + 1;
      }
      const close = source.indexOf("}", afterKind + 1);
      if (close !== -1 && isUnicodePropertyName(source.slice(afterKind + 1, close))) {
        return close;
      }
      return backslashIndex + 1;
    }
    if (kind === "u" && source[afterKind] === "{") {
      if (!unicodeMode) {
        return backslashIndex + 1;
      }
      const close = source.indexOf("}", afterKind + 1);
      if (close !== -1 && /^[0-9a-fA-F]{1,6}$/.test(source.slice(afterKind + 1, close))) {
        const cp = Number.parseInt(source.slice(afterKind + 1, close), 16);
        if (Number.isFinite(cp) && cp >= 0 && cp <= 1114111) {
          return close;
        }
      }
      return backslashIndex + 1;
    }
    if (kind === "u" && /^[0-9a-fA-F]{4}/.test(source.slice(afterKind, afterKind + 4))) {
      return afterKind + 3;
    }
    if (kind === "x" && /^[0-9a-fA-F]{2}/.test(source.slice(afterKind, afterKind + 2))) {
      return afterKind + 1;
    }
    const backref = readDecimalBackref(source, backslashIndex, captureCount);
    if (backref) {
      return backref.nextIndex - 1;
    }
    const octal = readLegacyOctalEscape(source, backslashIndex, unicodeMode);
    if (octal) {
      return octal.nextIndex - 1;
    }
    return backslashIndex + 1;
  }
  function readDecimalBackref(source, index, captureCount) {
    if (captureCount <= 0 || source[index] !== "\\") {
      return null;
    }
    const first = source[index + 1];
    if (first === void 0 || first < "1" || first > "9") {
      return null;
    }
    let end = index + 1;
    while (end + 1 < source.length) {
      const next = source[end + 1];
      if (next === void 0 || next < "0" || next > "9") {
        break;
      }
      end += 1;
    }
    const n = Number.parseInt(source.slice(index + 1, end + 1), 10);
    if (!Number.isFinite(n) || n > captureCount) {
      return null;
    }
    return { nextIndex: end + 1 };
  }
  function readLegacyOctalEscape(source, index, unicodeMode) {
    if (unicodeMode || source[index] !== "\\") {
      return null;
    }
    const kind = source[index + 1];
    if (kind === void 0 || kind < "0" || kind > "7") {
      return null;
    }
    let end = index + 1;
    const maxExtra = kind <= "3" ? 2 : 1;
    for (let extra = 0; extra < maxExtra; extra += 1) {
      const next = source[end + 1];
      if (next === void 0 || next < "0" || next > "7") {
        break;
      }
      end += 1;
    }
    return {
      value: String.fromCharCode(Number.parseInt(source.slice(index + 1, end + 1), 8)),
      nextIndex: end + 1
    };
  }
  function readUnambiguousOctalEscape(source, index, unicodeMode, captureCount = 0) {
    if (readDecimalBackref(source, index, captureCount)) {
      return null;
    }
    const octal = readLegacyOctalEscape(source, index, unicodeMode);
    if (!octal) {
      return null;
    }
    const digits = source.slice(index + 1, octal.nextIndex);
    const first = digits[0];
    const twoDigitHighOctal = digits.length === 2 && first !== void 0 && first >= "4" && first <= "7";
    if (digits.length < 3 && !digits.startsWith("0") && !twoDigitHighOctal) {
      return null;
    }
    return octal;
  }
  function readScalarEscape(source, index, unicodeMode = false, captureCount = 0) {
    if (source[index] !== "\\") {
      return null;
    }
    const kind = source[index + 1];
    if (kind === "u" && source[index + 2] === "{") {
      if (!unicodeMode) {
        return null;
      }
      const close = source.indexOf("}", index + 3);
      if (close < 0) {
        return null;
      }
      const hex = source.slice(index + 3, close);
      if (!/^[0-9a-fA-F]{1,6}$/.test(hex)) {
        return null;
      }
      const cp = Number.parseInt(hex, 16);
      if (!Number.isFinite(cp) || cp < 0 || cp > 1114111) {
        return null;
      }
      return { value: String.fromCodePoint(cp), nextIndex: close + 1 };
    }
    if (kind === "u" && /^[0-9a-fA-F]{4}/.test(source.slice(index + 2, index + 6))) {
      const cp = Number.parseInt(source.slice(index + 2, index + 6), 16);
      return { value: String.fromCodePoint(cp), nextIndex: index + 6 };
    }
    if (kind === "x" && /^[0-9a-fA-F]{2}/.test(source.slice(index + 2, index + 4))) {
      const cp = Number.parseInt(source.slice(index + 2, index + 4), 16);
      return { value: String.fromCharCode(cp), nextIndex: index + 4 };
    }
    return readUnambiguousOctalEscape(source, index, unicodeMode, captureCount);
  }
  function isCapturingGroupOpen(source, contentStart) {
    let open = contentStart - 1;
    while (open >= 0 && source[open] !== "(") {
      open -= 1;
    }
    if (open < 0) {
      return false;
    }
    if (source[open + 1] !== "?") {
      return true;
    }
    const marker = source[open + 2];
    if (marker === ":" || marker === "=" || marker === "!") {
      return false;
    }
    if (marker === "<" && (source[open + 3] === "=" || source[open + 3] === "!")) {
      return false;
    }
    return true;
  }
  function countCapturingGroups(source, tokens) {
    let count = 0;
    for (const token of tokens) {
      if (token.kind === "group-open" && isCapturingGroupOpen(source, token.contentStart)) {
        count += 1;
      }
    }
    return count;
  }
  function tokenizePatternWithCaptures(source, unicodeMode, captureCount) {
    const tokens = [];
    for (let i = 0; i < source.length; i += 1) {
      const ch = source[i];
      if (ch === "\\") {
        const end = readEscapeAtomEnd(source, i, unicodeMode, captureCount);
        tokens.push({ kind: "simple-token", source: source.slice(i, end + 1) });
        i = end;
        continue;
      }
      if (ch === "[") {
        const start = i;
        i += 1;
        while (i < source.length) {
          if (source[i] === "\\") {
            i += 2;
            continue;
          }
          if (source[i] === "]") {
            break;
          }
          i += 1;
        }
        tokens.push({
          kind: "simple-token",
          source: source.slice(start, Math.min(i + 1, source.length))
        });
        continue;
      }
      if (ch === "(") {
        const contentStart = readGroupContentStart(source, i);
        tokens.push({ kind: "group-open", contentStart });
        i = contentStart - 1;
        continue;
      }
      if (ch === ")") {
        tokens.push({ kind: "group-close", start: i });
        continue;
      }
      if (ch === "|") {
        tokens.push({ kind: "alternation", start: i, end: i + 1 });
        continue;
      }
      const quantifier = readQuantifier(source, i);
      if (quantifier) {
        tokens.push({ kind: "quantifier", quantifier });
        i += quantifier.consumed - 1;
        continue;
      }
      tokens.push({ kind: "simple-token", source: source.slice(i, i + 1) });
    }
    return tokens;
  }
  function tokenizePattern(source, flags = "", captureCount) {
    const unicodeMode = flags.includes("u") || flags.includes("v");
    if (captureCount === void 0) {
      const firstPass = tokenizePatternWithCaptures(source, unicodeMode, 0);
      const counted = countCapturingGroups(source, firstPass);
      if (counted === 0) {
        return firstPass;
      }
      return tokenizePatternWithCaptures(source, unicodeMode, counted);
    }
    return tokenizePatternWithCaptures(source, unicodeMode, captureCount);
  }
  var ZERO_WIDTH_SIMPLE_ATOMS = /* @__PURE__ */ new Set(["^", "$", "\\b", "\\B"]);
  var NAMED_CHAR_ESCAPES = {
    "\\n": "\n",
    "\\t": "	",
    "\\r": "\r",
    "\\f": "\f",
    "\\v": "\v"
  };
  function isLookaroundGroupPrefix(source, contentStart) {
    const prefix = source.slice(0, contentStart);
    return prefix.endsWith("?=") || prefix.endsWith("?!") || prefix.endsWith("?<=") || prefix.endsWith("?<!");
  }
  function findMatchingGroupClose(tokens, openIndex) {
    let depth = 0;
    for (let index = openIndex; index < tokens.length; index += 1) {
      const token = tokens[index];
      if (!token) {
        return -1;
      }
      if (token.kind === "group-open") {
        depth += 1;
      } else if (token.kind === "group-close") {
        depth -= 1;
        if (depth === 0) {
          return index;
        }
      }
    }
    return -1;
  }
  function escapeDecodedLiteral(value, unicodeMode) {
    let escaped = "";
    for (const ch of value) {
      const code = ch.codePointAt(0);
      if (code === void 0) {
        continue;
      }
      if (code < 256) {
        escaped += `\\x${code.toString(16).padStart(2, "0")}`;
        continue;
      }
      if (code < 65536) {
        escaped += `\\u${code.toString(16).padStart(4, "0")}`;
        continue;
      }
      if (unicodeMode) {
        escaped += `\\u{${code.toString(16)}}`;
        continue;
      }
      const units = String.fromCodePoint(code);
      for (let index = 0; index < units.length; index += 1) {
        escaped += `\\u${units.charCodeAt(index).toString(16).padStart(4, "0")}`;
      }
    }
    return escaped;
  }
  function decodeFixedWidthSimpleToken(source, unicodeMode, captureCount) {
    if (!source.startsWith("\\")) {
      return source;
    }
    if (/^\\x[0-9a-fA-F]{2}$/.test(source)) {
      return escapeDecodedLiteral(
        String.fromCharCode(Number.parseInt(source.slice(2), 16)),
        unicodeMode
      );
    }
    if (/^\\u[0-9a-fA-F]{4}$/.test(source)) {
      return escapeDecodedLiteral(
        String.fromCharCode(Number.parseInt(source.slice(2), 16)),
        unicodeMode
      );
    }
    if (unicodeMode && /^\\u\{[0-9a-fA-F]{1,6}\}$/.test(source)) {
      const cp = Number.parseInt(source.slice(3, -1), 16);
      if (!Number.isFinite(cp) || cp < 0 || cp > 1114111) {
        return null;
      }
      return escapeDecodedLiteral(String.fromCodePoint(cp), unicodeMode);
    }
    const octal = readUnambiguousOctalEscape(source, 0, unicodeMode, captureCount);
    if (octal && octal.nextIndex === source.length) {
      return escapeDecodedLiteral(octal.value, unicodeMode);
    }
    const named = NAMED_CHAR_ESCAPES[source];
    if (named !== void 0) {
      return escapeDecodedLiteral(named, unicodeMode);
    }
    if (source.length === 2) {
      const escaped = source[1];
      if (escaped !== void 0 && !/[0-9A-Za-z]/.test(escaped)) {
        return escapeDecodedLiteral(escaped, unicodeMode);
      }
      if (!unicodeMode && (source === "\\p" || source === "\\P") && escaped !== void 0) {
        return escapeDecodedLiteral(escaped, unicodeMode);
      }
    }
    if (/^\\[dDsSwW]$/.test(source) || source.startsWith("\\p{") || source.startsWith("\\P{")) {
      return source;
    }
    return null;
  }
  function sequenceOverlapIsProven(leftSeq, rightSeq) {
    if (leftSeq.atoms.length < rightSeq.atoms.length) {
      return leftSeq.complete;
    }
    if (rightSeq.atoms.length < leftSeq.atoms.length) {
      return rightSeq.complete;
    }
    return true;
  }
  var ATOM_SEQUENCE_OVERFLOW = "overflow";
  var MAX_ALTERNATIVE_SEQUENCES = 16;
  var MAX_SEQUENCE_ATOMS = 32;
  function splitTopLevelAlternativeSources(source, unicodeMode, captureCount) {
    const tokens = tokenizePattern(source, unicodeMode ? "u" : "", captureCount);
    const cuts = [];
    let depth = 0;
    for (const token of tokens) {
      if (token.kind === "group-open") {
        depth += 1;
        continue;
      }
      if (token.kind === "group-close") {
        depth -= 1;
        continue;
      }
      if (token.kind === "alternation" && depth === 0) {
        cuts.push(token.start);
      }
    }
    if (cuts.length === 0) {
      return [source];
    }
    const parts = [];
    let start = 0;
    for (const cut of cuts) {
      parts.push(source.slice(start, cut));
      start = cut + 1;
    }
    parts.push(source.slice(start));
    return parts;
  }
  function cartesianConcatSequences(left, right) {
    if (left.length === 0) {
      return right.map((seq) => ({ atoms: [...seq.atoms], complete: seq.complete }));
    }
    if (right.length === 0) {
      return left.map((seq) => ({ atoms: [...seq.atoms], complete: seq.complete }));
    }
    if (left.length * right.length > MAX_ALTERNATIVE_SEQUENCES) {
      return ATOM_SEQUENCE_OVERFLOW;
    }
    const out = [];
    for (const prefix of left) {
      for (const suffix of right) {
        const combinedLength = prefix.atoms.length + suffix.atoms.length;
        if (combinedLength > MAX_SEQUENCE_ATOMS) {
          const room = MAX_SEQUENCE_ATOMS - prefix.atoms.length;
          out.push({
            atoms: room > 0 ? [...prefix.atoms, ...suffix.atoms.slice(0, room)] : [...prefix.atoms],
            complete: false
          });
          continue;
        }
        out.push({
          atoms: [...prefix.atoms, ...suffix.atoms],
          complete: prefix.complete && suffix.complete
        });
      }
    }
    return out;
  }
  function collectAtomSequences(source, unicodeMode, captureCount) {
    const tokens = tokenizePattern(source, unicodeMode ? "u" : "", captureCount);
    let sequences = [{ atoms: [], complete: true }];
    for (let index = 0; index < tokens.length; ) {
      const token = tokens[index];
      if (!token) {
        return null;
      }
      if (token.kind === "quantifier" || token.kind === "alternation" || token.kind === "group-close") {
        return null;
      }
      if (token.kind === "group-open") {
        const closeIndex = findMatchingGroupClose(tokens, index);
        const close = tokens[closeIndex];
        if (closeIndex < 0 || !close || close.kind !== "group-close") {
          return null;
        }
        const contentStart = token.contentStart;
        if (isLookaroundGroupPrefix(source, contentStart)) {
          index = closeIndex + 1;
          continue;
        }
        const interior = source.slice(contentStart, close.start);
        const inner = interior ? readAlternativeAtomSequences(interior, unicodeMode, captureCount) : [{ atoms: [], complete: true }];
        if (inner === ATOM_SEQUENCE_OVERFLOW) {
          return ATOM_SEQUENCE_OVERFLOW;
        }
        if (!inner) {
          return null;
        }
        const next2 = cartesianConcatSequences(sequences, inner);
        if (next2 === ATOM_SEQUENCE_OVERFLOW) {
          return ATOM_SEQUENCE_OVERFLOW;
        }
        sequences = next2;
        index = closeIndex + 1;
        continue;
      }
      if (ZERO_WIDTH_SIMPLE_ATOMS.has(token.source)) {
        index += 1;
        continue;
      }
      const decoded = decodeFixedWidthSimpleToken(token.source, unicodeMode, captureCount);
      if (decoded === null) {
        return null;
      }
      const next = cartesianConcatSequences(sequences, [{ atoms: [decoded], complete: true }]);
      if (next === ATOM_SEQUENCE_OVERFLOW) {
        return ATOM_SEQUENCE_OVERFLOW;
      }
      sequences = next;
      index += 1;
    }
    const nonempty = sequences.filter((seq) => seq.atoms.length > 0);
    return nonempty.length > 0 ? nonempty : null;
  }
  function stripAlternativeAnchors(source) {
    let start = 0;
    let end = source.length;
    if (source[start] === "^") {
      start += 1;
    }
    if (end > start && source[end - 1] === "$") {
      let slashes = 0;
      for (let i = end - 2; i >= start && source[i] === "\\"; i -= 1) {
        slashes += 1;
      }
      if (slashes % 2 === 0) {
        end -= 1;
      }
    }
    return source.slice(start, end);
  }
  function readAlternativeAtomSequences(source, unicodeMode = false, captureCount = 0) {
    const body = stripAlternativeAnchors(source);
    if (!body) {
      return null;
    }
    const parts = splitTopLevelAlternativeSources(body, unicodeMode, captureCount);
    if (parts.length === 1) {
      return collectAtomSequences(body, unicodeMode, captureCount);
    }
    const all = [];
    for (const part of parts) {
      const sequences = collectAtomSequences(part, unicodeMode, captureCount);
      if (sequences === ATOM_SEQUENCE_OVERFLOW) {
        return ATOM_SEQUENCE_OVERFLOW;
      }
      if (!sequences) {
        return null;
      }
      if (all.length + sequences.length > MAX_ALTERNATIVE_SEQUENCES) {
        return ATOM_SEQUENCE_OVERFLOW;
      }
      all.push(...sequences);
    }
    return all;
  }

  // src/security/safe-regex-adjacent.ts
  function isZeroWidthAtom(language) {
    return language === "" || language === "^" || language === "$" || language === "\\b" || language === "\\B" || language === "(?:)" || language === "(?=)" || language === "(?!)" || language === "(?<=)" || language === "(?<!)";
  }
  function isZeroWidthLanguage(language, alternatives) {
    return isZeroWidthAtom(language) || alternatives.every((alt) => isZeroWidthAtom(alt));
  }
  function unionPendingAlts(left, right) {
    const seen = new Set(left);
    const out = [...left];
    for (const alt of right) {
      if (!seen.has(alt)) {
        seen.add(alt);
        out.push(alt);
      }
    }
    return out;
  }
  function nextPendingAdjacentAlts(previous, newAlts, minRepeat, maxRepeat, isZeroWidth) {
    if (isZeroWidth) {
      return previous;
    }
    if (maxRepeat === null && newAlts.length > 0) {
      if (minRepeat === 0 && previous) {
        return unionPendingAlts(previous, newAlts);
      }
      return [...newAlts];
    }
    if (minRepeat === 0) {
      return previous;
    }
    return null;
  }
  function isLookaroundPrefix(source, contentStart) {
    const prefix = source.slice(Math.max(0, contentStart - 4), contentStart);
    return prefix.endsWith("?=") || prefix.endsWith("?!") || prefix.endsWith("?<=") || prefix.endsWith("?<!");
  }
  function walkRegexSource(source, visit) {
    let depth = 0;
    let inClass = false;
    for (let index = 0; index < source.length; index += 1) {
      const ch = source[index];
      if (ch === void 0) {
        continue;
      }
      if (ch === "\\") {
        index += 1;
        continue;
      }
      if (inClass) {
        if (ch === "]") {
          inClass = false;
        }
        continue;
      }
      if (ch === "[") {
        inClass = true;
        continue;
      }
      if (ch === "(") {
        depth += 1;
        visit(ch, index, depth);
        continue;
      }
      if (ch === ")") {
        depth -= 1;
        if (depth < 0) {
          return false;
        }
        visit(ch, index, depth);
        continue;
      }
      visit(ch, index, depth);
    }
    return depth === 0;
  }
  function isSingleWrappingGroup(source) {
    if (source.length < 2 || source[0] !== "(" || source[source.length - 1] !== ")") {
      return false;
    }
    let closedEarly = false;
    const balanced = walkRegexSource(source, (ch, index, depth) => {
      if (ch === ")" && depth === 0 && index !== source.length - 1) {
        closedEarly = true;
      }
    });
    return balanced && !closedEarly;
  }
  function tryUnwrapOuterGroup(source) {
    if (!isSingleWrappingGroup(source)) {
      return null;
    }
    if (source.startsWith("(?=") || source.startsWith("(?!") || source.startsWith("(?<=")) {
      return null;
    }
    if (source.startsWith("(?:")) {
      return source.slice(3, -1);
    }
    if (source.startsWith("(?")) {
      return null;
    }
    return source.slice(1, -1);
  }
  function splitTopLevelAlternatives(source) {
    const cuts = [];
    walkRegexSource(source, (ch, index, depth) => {
      if (ch === "|" && depth === 0) {
        cuts.push(index);
      }
    });
    if (cuts.length === 0) {
      return [source];
    }
    const parts = [];
    let start = 0;
    for (const cut of cuts) {
      parts.push(source.slice(start, cut));
      start = cut + 1;
    }
    parts.push(source.slice(start));
    return parts;
  }
  function flattenAlternatives(alternatives) {
    const out = [];
    const seen = /* @__PURE__ */ new Set();
    const visit = (raw) => {
      let current = raw;
      for (let depth = 0; depth < 8; depth += 1) {
        const inner = tryUnwrapOuterGroup(current);
        if (inner === null) {
          break;
        }
        current = inner;
      }
      const parts = splitTopLevelAlternatives(current);
      if (parts.length > 1) {
        for (const part of parts) {
          visit(part);
        }
        return;
      }
      if (!seen.has(current)) {
        seen.add(current);
        out.push(current);
      }
    };
    for (const alternative of alternatives) {
      visit(alternative);
    }
    return out.length > 0 ? out : [""];
  }
  function sameAlternativeSet(left, right) {
    if (left.length !== right.length) {
      return false;
    }
    const sortedLeft = [...left].toSorted();
    const sortedRight = [...right].toSorted();
    return sortedLeft.every((alt, index) => alt === sortedRight[index]);
  }
  function isCharacterClassAlternative(source) {
    let body = source;
    if (body.startsWith("^")) {
      body = body.slice(1);
    }
    if (body.endsWith("$")) {
      body = body.slice(0, -1);
    }
    return body.startsWith("[") && body.endsWith("]") && body.length >= 2;
  }
  function shouldRejectAdjacentOverlap(leftAlts, rightAlts, ignoreCase, failClosedUnprobedUnicode, singleTokenPairOverlaps) {
    if (!adjacentRepeatsOverlap(leftAlts, rightAlts, ignoreCase, singleTokenPairOverlaps)) {
      return false;
    }
    if (!failClosedUnprobedUnicode && sameAlternativeSet(leftAlts, rightAlts) && leftAlts.every((alt) => isCharacterClassAlternative(alt))) {
      return false;
    }
    return true;
  }
  function adjacentRepeatsOverlap(leftAlts, rightAlts, ignoreCase, singleTokenPairOverlaps) {
    const leftFlat = flattenAlternatives(leftAlts);
    const rightFlat = flattenAlternatives(rightAlts);
    for (const left of leftFlat) {
      for (const right of rightFlat) {
        if (left === right) {
          return true;
        }
        if (singleTokenPairOverlaps(left, right, ignoreCase)) {
          return true;
        }
      }
    }
    return false;
  }
  function mixedSequencesOverlap(leftAtoms, rightAtoms, ignoreCase, failClosedUnprobedUnicode, singleTokenPairOverlaps) {
    const sharedLength = Math.min(leftAtoms.length, rightAtoms.length);
    for (let index = 0; index < sharedLength; index += 1) {
      const leftAtom = leftAtoms[index];
      const rightAtom = rightAtoms[index];
      if (leftAtom === void 0 || rightAtom === void 0) {
        return true;
      }
      if (!singleTokenPairOverlaps(leftAtom, rightAtom, ignoreCase, failClosedUnprobedUnicode)) {
        return false;
      }
    }
    return true;
  }
  function alternativeHasUnprobedNonAscii(source, captureCount = 0) {
    const body = stripAlternativeAnchors(source);
    let decoded = "";
    for (let index = 0; index < body.length; index += 1) {
      if (body[index] === "\\") {
        const scalar = readScalarEscape(body, index, false, captureCount);
        if (scalar) {
          decoded += scalar.value;
          index = scalar.nextIndex - 1;
          continue;
        }
        if (body[index + 1] === "p" || body[index + 1] === "P") {
          return true;
        }
        if (body[index + 1] === "u" && body[index + 2] === "{") {
          return true;
        }
        decoded += body[index];
        continue;
      }
      decoded += body[index];
    }
    for (let i = 0; i < decoded.length; i += 1) {
      if (decoded.charCodeAt(i) > 127) {
        return true;
      }
    }
    return false;
  }
  function isUnicodePropertyAtom(source) {
    const body = stripAlternativeAnchors(source);
    const inner = body.startsWith("[") && body.endsWith("]") && !body.slice(1, -1).includes("[") ? body.slice(1, -1) : body;
    return /^\\[pP]\{[A-Za-z_][A-Za-z0-9_]*(=[A-Za-z0-9_]+)?\}$/.test(inner);
  }
  function singleTokenAlternativesMayOverlap(left, right, ignoreCase, failClosedUnprobedUnicode, unicodeMode = false, dotAll = false) {
    const flags = `${ignoreCase ? "i" : ""}${unicodeMode ? "u" : ""}${dotAll ? "s" : ""}`;
    let leftRe;
    let rightRe;
    try {
      leftRe = new RegExp(`^(?:${stripAlternativeAnchors(left)})$`, flags);
      rightRe = new RegExp(`^(?:${stripAlternativeAnchors(right)})$`, flags);
    } catch {
      return true;
    }
    let leftHit = false;
    let rightHit = false;
    const consider = (ch) => {
      const leftMatch = leftRe.test(ch);
      const rightMatch = rightRe.test(ch);
      if (leftMatch) {
        leftHit = true;
      }
      if (rightMatch) {
        rightHit = true;
      }
      return leftMatch && rightMatch;
    };
    for (let code = 0; code < 128; code += 1) {
      if (consider(String.fromCharCode(code))) {
        return true;
      }
    }
    for (const ch of ["\xA0", "\xE9", "\u4E2D"]) {
      if (consider(ch)) {
        return true;
      }
    }
    if (isUnicodePropertyAtom(left) && isUnicodePropertyAtom(right) && !leftHit && !rightHit) {
      return true;
    }
    if (failClosedUnprobedUnicode && (alternativeHasUnprobedNonAscii(left) || alternativeHasUnprobedNonAscii(right))) {
      return true;
    }
    return false;
  }

  // src/security/safe-regex.ts
  var SAFE_REGEX_CACHE_MAX = 256;
  var safeRegexCache = /* @__PURE__ */ new Map();
  function createParseFrame(contentStart = 0) {
    return {
      lastToken: null,
      containsRepetition: false,
      containsAmbiguousAlternation: false,
      hasAlternation: false,
      hasOverlappingAlternative: false,
      alternativeSources: [],
      contentStart,
      branchStart: contentStart,
      branchMinLength: 0,
      branchMaxLength: 0,
      branchTokenCount: 0,
      altMinLength: null,
      altMaxLength: null,
      pendingAdjacentAlts: null,
      pendingNextAlts: null
    };
  }
  function addLength(left, right) {
    if (!Number.isFinite(left) || !Number.isFinite(right)) {
      return Number.POSITIVE_INFINITY;
    }
    return left + right;
  }
  function multiplyLength(length, factor) {
    if (!Number.isFinite(length)) {
      return factor === 0 ? 0 : Number.POSITIVE_INFINITY;
    }
    return length * factor;
  }
  function escapeRegExpLiteral(value) {
    return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  }
  function readAlternativeLiteral(source, unicodeMode = false, captureCount = 0) {
    let value = "";
    for (let index = 0; index < source.length; index += 1) {
      const ch = source[index];
      if (ch === "^" || ch === "$") {
        continue;
      }
      if (ch === "\\") {
        const scalar = readScalarEscape(source, index, unicodeMode, captureCount);
        if (scalar) {
          value += scalar.value;
          index = scalar.nextIndex - 1;
          continue;
        }
        const escaped = source[index + 1];
        if (escaped === "b" || escaped === "B") {
          index += 1;
          continue;
        }
        if (escaped !== void 0 && !/[0-9A-Za-z]/.test(escaped)) {
          value += escaped;
          index += 1;
          continue;
        }
        return { kind: "broad" };
      }
      if (ch === "." || ch === "[" || ch === "(" || ch === ")" || ch === "|" || ch === "*" || ch === "+" || ch === "?" || ch === "{") {
        return { kind: "broad" };
      }
      value += ch;
    }
    return value.length === 0 ? { kind: "broad" } : { kind: "literal", value };
  }
  function isSingleTokenAlternative(source, unicodeMode = false, captureCount = 0) {
    let tokens = 0;
    for (let index = 0; index < source.length; index += 1) {
      const ch = source[index];
      if (ch === "^" || ch === "$") {
        continue;
      }
      if (ch === "\\") {
        tokens += 1;
        index = readEscapeAtomEnd(source, index, unicodeMode, captureCount);
        if (tokens > 1) {
          return false;
        }
        continue;
      }
      if (ch === "[") {
        tokens += 1;
        if (tokens > 1) {
          return false;
        }
        let depth = 1;
        index += 1;
        while (index < source.length && depth > 0) {
          if (source[index] === "\\") {
            index += 2;
            continue;
          }
          if (source[index] === "[") {
            depth += 1;
          } else if (source[index] === "]") {
            depth -= 1;
          }
          index += 1;
        }
        index -= 1;
        continue;
      }
      if (ch === "(" || ch === ")" || ch === "|" || ch === "*" || ch === "+" || ch === "?" || ch === "{" || ch === ".") {
        return false;
      }
      tokens += 1;
      if (tokens > 1) {
        return false;
      }
    }
    return tokens === 1;
  }
  function alternativesMayOverlap(left, right, ignoreCase, failClosedUnprobedUnicode, unicodeMode = false, captureCount = 0, dotAll = false) {
    const leftLit = readAlternativeLiteral(left, unicodeMode, captureCount);
    const rightLit = readAlternativeLiteral(right, unicodeMode, captureCount);
    if (leftLit.kind === "literal" && rightLit.kind === "literal") {
      const a = leftLit.value;
      const b = rightLit.value;
      if (!ignoreCase) {
        return a === b || a.startsWith(b) || b.startsWith(a);
      }
      try {
        const shorter = a.length <= b.length ? a : b;
        const longer = a.length <= b.length ? b : a;
        return new RegExp(`^${escapeRegExpLiteral(shorter)}`, "iu").test(longer);
      } catch {
        return true;
      }
    }
    if (isSingleTokenAlternative(left, unicodeMode, captureCount) && isSingleTokenAlternative(right, unicodeMode, captureCount)) {
      return singleTokenAlternativesMayOverlap(
        left,
        right,
        ignoreCase,
        failClosedUnprobedUnicode,
        unicodeMode,
        dotAll
      );
    }
    const leftSequences = readAlternativeAtomSequences(left, unicodeMode, captureCount);
    const rightSequences = readAlternativeAtomSequences(right, unicodeMode, captureCount);
    if (leftSequences === ATOM_SEQUENCE_OVERFLOW || rightSequences === ATOM_SEQUENCE_OVERFLOW) {
      return false;
    }
    if (leftSequences && rightSequences) {
      let unproven = false;
      for (const leftSeq of leftSequences) {
        for (const rightSeq of rightSequences) {
          if (!mixedSequencesOverlap(
            leftSeq.atoms,
            rightSeq.atoms,
            ignoreCase,
            failClosedUnprobedUnicode,
            (leftAtom, rightAtom, ignoreCaseFlag, failClosed) => singleTokenAlternativesMayOverlap(
              leftAtom,
              rightAtom,
              ignoreCaseFlag,
              failClosed,
              unicodeMode,
              dotAll
            )
          )) {
            continue;
          }
          if (sequenceOverlapIsProven(leftSeq, rightSeq)) {
            return true;
          }
          unproven = true;
        }
      }
      return unproven && failClosedUnprobedUnicode;
    }
    return true;
  }
  function recordAlternative(frame, source, branchEnd, ignoreCase, failClosedUnprobedUnicode, unicodeMode, captureCount, dotAll) {
    const branchSource = source.slice(frame.branchStart, branchEnd);
    if (frame.alternativeSources.some(
      (alternative) => alternativesMayOverlap(
        alternative,
        branchSource,
        ignoreCase,
        failClosedUnprobedUnicode,
        unicodeMode,
        captureCount,
        dotAll
      )
    )) {
      frame.hasOverlappingAlternative = true;
    }
    frame.alternativeSources.push(branchSource);
    if (frame.altMinLength === null || frame.altMaxLength === null) {
      frame.altMinLength = frame.branchMinLength;
      frame.altMaxLength = frame.branchMaxLength;
      return;
    }
    frame.altMinLength = Math.min(frame.altMinLength, frame.branchMinLength);
    frame.altMaxLength = Math.max(frame.altMaxLength, frame.branchMaxLength);
  }
  function adjacentPairOverlaps(left, right, ignoreCase, unicodeMode = false, captureCount = 0, dotAll = false) {
    return isSingleTokenAlternative(left, unicodeMode, captureCount) && isSingleTokenAlternative(right, unicodeMode, captureCount) && alternativesMayOverlap(left, right, ignoreCase, false, unicodeMode, captureCount, dotAll);
  }
  function analyzeTokensForNestedRepetition(source, tokens, ignoreCase, failClosedUnprobedUnicode, unicodeMode, captureCount, dotAll) {
    const pairOverlaps = (left, right, ignoreCaseFlag) => adjacentPairOverlaps(left, right, ignoreCaseFlag, unicodeMode, captureCount, dotAll);
    const frames = [createParseFrame()];
    const emitToken = (token) => {
      const frame = expectDefined(frames[frames.length - 1], "frames entry at frames.length 1");
      frame.lastToken = token;
      if (token.containsRepetition) {
        frame.containsRepetition = true;
      }
      if (token.hasAmbiguousAlternation) {
        frame.containsAmbiguousAlternation = true;
      }
      frame.branchMinLength = addLength(frame.branchMinLength, token.minLength);
      frame.branchMaxLength = addLength(frame.branchMaxLength, token.maxLength);
      frame.branchTokenCount += 1;
    };
    const noteAdjacentAtom = (language, alternatives, minLength = 1) => {
      if (minLength === 0 || isZeroWidthLanguage(language, alternatives)) {
        return;
      }
      const frame = expectDefined(frames[frames.length - 1], "frames entry at frames.length 1");
      if (frame.pendingNextAlts !== null) {
        frame.pendingAdjacentAlts = null;
        frame.pendingNextAlts = null;
      } else if (frame.pendingAdjacentAlts !== null) {
        frame.pendingNextAlts = alternatives;
      }
    };
    const emitSimpleToken = (language) => {
      const alternatives = [language];
      noteAdjacentAtom(language, alternatives);
      emitToken({
        containsRepetition: false,
        hasAmbiguousAlternation: false,
        minLength: 1,
        maxLength: 1,
        language,
        alternatives
      });
    };
    for (const token of tokens) {
      if (token.kind === "simple-token") {
        emitSimpleToken(token.source);
        continue;
      }
      if (token.kind === "group-open") {
        frames.push(createParseFrame(token.contentStart));
        continue;
      }
      if (token.kind === "group-close") {
        if (frames.length > 1) {
          const frame2 = frames.pop();
          const parent = expectDefined(frames[frames.length - 1], "frames entry at frames.length 1");
          if (isLookaroundPrefix(source, frame2.contentStart)) {
            noteAdjacentAtom("(?=)", ["(?=)"]);
            emitToken({
              containsRepetition: false,
              hasAmbiguousAlternation: false,
              minLength: 0,
              maxLength: 0,
              language: "(?=)",
              alternatives: ["(?=)"]
            });
            continue;
          }
          if (frame2.hasAlternation) {
            recordAlternative(
              frame2,
              source,
              token.start,
              ignoreCase,
              failClosedUnprobedUnicode,
              unicodeMode,
              captureCount,
              dotAll
            );
          }
          const groupMinLength = frame2.hasAlternation ? frame2.altMinLength ?? 0 : frame2.branchMinLength;
          const groupMaxLength = frame2.hasAlternation ? frame2.altMaxLength ?? 0 : frame2.branchMaxLength;
          const groupLanguage = (frame2.hasAlternation ? frame2.alternativeSources.join("|") : source.slice(frame2.contentStart, token.start)) || "(?:)";
          const groupAlts = frame2.hasAlternation && frame2.alternativeSources.length > 0 ? frame2.alternativeSources : frame2.branchTokenCount === 1 && frame2.lastToken?.alternatives && frame2.lastToken.alternatives.length > 0 ? frame2.lastToken.alternatives : [groupLanguage];
          const groupUnbounded = !Number.isFinite(groupMaxLength);
          if (groupUnbounded && parent.pendingAdjacentAlts && parent.pendingNextAlts === null && shouldRejectAdjacentOverlap(
            parent.pendingAdjacentAlts,
            groupAlts,
            ignoreCase,
            failClosedUnprobedUnicode,
            pairOverlaps
          )) {
            return true;
          }
          noteAdjacentAtom(groupLanguage, groupAlts, groupMinLength);
          emitToken({
            containsRepetition: frame2.containsRepetition,
            // Only mark ambiguous when alternatives may actually overlap.
            // Disjoint unequal lengths such as (a|bc)+ are safe and must remain
            // accepted (compatibility with main; Claw P1 on schema ReDoS guards).
            hasAmbiguousAlternation: frame2.containsAmbiguousAlternation || frame2.hasAlternation && frame2.hasOverlappingAlternative,
            minLength: groupMinLength,
            maxLength: groupMaxLength,
            language: groupLanguage,
            alternatives: groupAlts
          });
          if (groupUnbounded && !isZeroWidthLanguage(groupLanguage, groupAlts)) {
            parent.pendingAdjacentAlts = nextPendingAdjacentAlts(
              parent.pendingAdjacentAlts,
              groupAlts,
              groupMinLength === 0 ? 0 : 1,
              null,
              false
            );
            parent.pendingNextAlts = null;
          }
        }
        continue;
      }
      if (token.kind === "alternation") {
        const frame2 = expectDefined(frames[frames.length - 1], "frames entry at frames.length 1");
        frame2.hasAlternation = true;
        recordAlternative(
          frame2,
          source,
          token.start,
          ignoreCase,
          failClosedUnprobedUnicode,
          unicodeMode,
          captureCount,
          dotAll
        );
        frame2.branchStart = token.end;
        frame2.branchMinLength = 0;
        frame2.branchMaxLength = 0;
        frame2.branchTokenCount = 0;
        frame2.lastToken = null;
        frame2.pendingAdjacentAlts = null;
        frame2.pendingNextAlts = null;
        continue;
      }
      const frame = expectDefined(frames[frames.length - 1], "frames entry at frames.length 1");
      const previousToken = frame.lastToken;
      if (!previousToken) {
        continue;
      }
      if (frame.pendingAdjacentAlts && frame.pendingNextAlts && token.quantifier.maxRepeat === null && shouldRejectAdjacentOverlap(
        frame.pendingAdjacentAlts,
        frame.pendingNextAlts,
        ignoreCase,
        failClosedUnprobedUnicode,
        pairOverlaps
      )) {
        return true;
      }
      if (previousToken.containsRepetition) {
        return true;
      }
      if (previousToken.hasAmbiguousAlternation && token.quantifier.maxRepeat === null) {
        return true;
      }
      const previousMinLength = previousToken.minLength;
      const previousMaxLength = previousToken.maxLength;
      previousToken.minLength = multiplyLength(previousToken.minLength, token.quantifier.minRepeat);
      previousToken.maxLength = token.quantifier.maxRepeat === null ? Number.POSITIVE_INFINITY : multiplyLength(previousToken.maxLength, token.quantifier.maxRepeat);
      previousToken.containsRepetition = true;
      frame.containsRepetition = true;
      frame.branchMinLength = frame.branchMinLength - previousMinLength + previousToken.minLength;
      const branchMaxBase = Number.isFinite(frame.branchMaxLength) && Number.isFinite(previousMaxLength) ? frame.branchMaxLength - previousMaxLength : Number.POSITIVE_INFINITY;
      frame.branchMaxLength = addLength(branchMaxBase, previousToken.maxLength);
      const previousLanguage = previousToken.language ?? "";
      frame.pendingAdjacentAlts = nextPendingAdjacentAlts(
        frame.pendingAdjacentAlts,
        previousToken.alternatives,
        token.quantifier.minRepeat,
        token.quantifier.maxRepeat,
        isZeroWidthLanguage(previousLanguage, previousToken.alternatives)
      );
      frame.pendingNextAlts = null;
    }
    return false;
  }
  function hasUnsafeRepetition(source, flags, failClosedUnprobedUnicode) {
    const unicodeMode = flags.includes("u") || flags.includes("v");
    const tokens = tokenizePattern(source, flags);
    return analyzeTokensForNestedRepetition(
      source,
      tokens,
      flags.includes("i"),
      failClosedUnprobedUnicode,
      unicodeMode,
      countCapturingGroups(source, tokens),
      flags.includes("s")
    );
  }
  function compileSafeRegexDetailedImpl(source, flags, failClosedUnprobedUnicode) {
    const trimmed = source.trim();
    if (!trimmed) {
      return { regex: null, source: trimmed, flags, reason: "empty" };
    }
    const cacheKey = `${failClosedUnprobedUnicode ? "exec" : "shared"}::${flags}::${trimmed}`;
    if (safeRegexCache.has(cacheKey)) {
      return safeRegexCache.get(cacheKey) ?? {
        regex: null,
        source: trimmed,
        flags,
        reason: "invalid-regex"
      };
    }
    let result;
    if (hasUnsafeRepetition(trimmed, flags, failClosedUnprobedUnicode)) {
      result = { regex: null, source: trimmed, flags, reason: "unsafe-nested-repetition" };
    } else {
      try {
        result = { regex: new RegExp(trimmed, flags), source: trimmed, flags, reason: null };
      } catch {
        result = { regex: null, source: trimmed, flags, reason: "invalid-regex" };
      }
    }
    safeRegexCache.set(cacheKey, result);
    pruneMapToMaxSize(safeRegexCache, SAFE_REGEX_CACHE_MAX);
    return result;
  }
  function compileSafeRegexDetailed(source, flags = "") {
    return compileSafeRegexDetailedImpl(source, flags, false);
  }
  function compileSafeRegexForExec(source, flags = "") {
    return compileSafeRegexDetailedImpl(source, flags, true);
  }

  // src/infra/exec-arg-pattern.ts
  function compileExecArgPattern(source) {
    const safety = compileSafeRegexForExec(source);
    if (safety.reason === "unsafe-nested-repetition") {
      return { regex: null, reason: "unsafe-nested-repetition" };
    }
    try {
      return { regex: new RegExp(source), reason: null };
    } catch {
      return { regex: null, reason: "invalid-regex" };
    }
  }
  function isConservativeExecArgPatternRefusal(source) {
    if (compileExecArgPattern(source).regex) {
      return false;
    }
    return compileSafeRegexDetailed(source).regex !== null;
  }
  return __toCommonJS(exec_arg_pattern_exports);
})();
"""#
}
